global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: goroxcore-monolith
    metrics_path: /metrics
    static_configs:
      - targets:
          - 127.0.0.1:8000

  - job_name: goroxcore-auth
    metrics_path: /metrics
    static_configs:
      - targets:
          - 127.0.0.1:8003

  - job_name: goroxcore-ticketing
    metrics_path: /metrics
    static_configs:
      - targets:
          - 127.0.0.1:8001

  - job_name: goroxcore-payment
    metrics_path: /metrics
    static_configs:
      - targets:
          - 127.0.0.1:8002
